services:
  geoheat_app:
    build: 
      dockerfile: ./geoheat.Dockerfile
    container_name: geoheat_flask
    restart: unless-stopped
    ports:
      - 5001:5000
    env_file:
      - .env
    networks:
      - geoheat_net
  geoheat_database:
    image: mongo:latest
    container_name: geoheat_mongodb
    restart: unless-stopped
    ports:
      - 27018:27017
    env_file:
      - .env
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
      - ./geoheat_db_data:/data/geoheat_db_data
    command: 
      - --storageEngine
      - wiredTiger
      - --auth
    networks:
      - geoheat_net
networks:
  geoheat_net:
    driver: bridge

    