services:
  geoheat_database:
    image: mongodb/mongodb-community-server:latest
    container_name: geoheat_mongodb
    ports:
      - 27018:27017
    env_file:
      - .env
    volumes:
      - D:\WorkSpace\GeoHeat\geoheat_db_data:/data/geoheat_db_data
      - D:\WorkSpace\GeoHeat\scripts:/data/geoheat_db_scripts
    command: ./data/geoheat_db_scripts/mongodb.sh
    restart: unless-stopped